### ISSUE TITLE
settings lost on restart

### ISSUE THREAD

**Issue by clarity99** [afterlogic/docker-webmail-lite#1]
If you don't set up a volume on /var/www/html (or perhaps /var/www/html/data) all your system settings get lost (db connection, imap/smtp servers,...).

**Comment by ivanperez-keera** [comment]
Yes, perhaps this could be clearer.

Perhaps a good addition to this image would be to declare a volume, subdir of the current path, that holds all the settings that this image will produce.

**Comment by chopfitzroy** [comment]
Ideally I would like to be able to persist any settings files as well as the DB.

**Comment by afterlogic-support** [comment]
Have just updated the Docker image, to make it work with current WebMail Lite, volumes are set up there, so the issue shouldn't be there anymore.
