### ISSUE TITLE
Container health check always fails

### ISSUE THREAD

**Issue by somescout** [afterlogic/docker-webmail-lite#10]
Hello.

Nginx in this package configured to listen port 80, but healthcheck in Dockerfile checks port 8080 and thus always fails:
`HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping`

Should be fixed to
`HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1/fpm-ping`

**Comment by afterlogic-support** [comment]
Thank you! We have fixed the issue in this repository and other related ones (such as [afterlogic/docker-webmail-pro](https://github.com/afterlogic/docker-webmail-pro)).

We're now working on releasing version 9.7.0 of the product, and once it's out, will be updating images at [DockerHub](https://hub.docker.com/r/afterlogic/docker-webmail-lite) too. Till then, keeping this issue open.

**Comment by afterlogic-support** [comment]
[Docker image for WebMail Lite](https://hub.docker.com/r/afterlogic/docker-webmail-lite), as well as other images we offer, are updated at DockerHub. Thanks again!
