### ISSUE TITLE
broken latest image

### ISSUE THREAD

**Issue by clarity99** [afterlogic/docker-webmail-lite#3]
After the latest image came out, the container gets stuck at:
server_1  | => Installing MySQL ...
server_1  | 200429 18:49:11 mysqld_safe Logging to syslog.
server_1  | 200429 18:49:11 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql

I can't see previous tags on the docker hub, so it's hard to revert. Can you either upload also previous image to dockerhub, or perhaps give some ideas on how to debug this? 

I suspect it might have something to do with these 2 volumes I have in my docker compose file for the image: 
volumes:
      - mysql:/var/lib/mysql
      - data:/var/www/html

**Comment by clarity99** [comment]
If I create a new empty volume, the container starts and initializes the db the first time, but unfortunately it re-initializes it every time after that is well, so after every restart all configuration is lost.

**Comment by clarity99** [comment]
I've added a pull request #4 that fixes the reinit problem. not sure how to fix the upgrade issue.

**Comment by afterlogic-support** [comment]
Thank you, will look into this. This is actually the first package for WebMail v8 we've uploaded to DockerHub, so there's no previous one for this version.
We're now doing a research on providing an updated image, most likely it'll be based on Alpine and will include newer PHP version, too. Still we're accepting this pull request of course, but I wonder what "upgrade issue" you're referring to? Thanks.

**Comment by clarity99** [comment]
Hi, well the previous version had the same name on docker hub and no tags. By upgrade issue I mean if you had the previous image running in the container with volumes for mysql and you pulled a new image, the new container didn't work.

**Comment by afterlogic-support** [comment]
We've just updated this to v9 and we believe the database update issue is corrected. Thanks.
