### ISSUE TITLE
Add environment variables for container

### ISSUE THREAD

**Issue by Troodi** [afterlogic/docker-webmail-lite#5]
Please, add environment variables for configure webmail. For example: default mail server, mail ports, etc... For autoconfigure webmail when docker-compose up.

**Comment by afterlogic-support** [comment]
Within next few weeks, we'll be updating docker images for WebMail Lite and other products. Recently, there was a [modification](https://github.com/afterlogic/docker-aurora-files/pull/9/commits/1fcf48be950ec7546f8755cdb19dc99b56bc21f9) submitted by one of the community members, that allows for overriding default configuration values, and we'll be adopting the modification for our WebMail products as well.
