### ISSUE TITLE
I can't integrate afterlogic webmail using docker

### ISSUE THREAD

**Issue by Sollydus** [afterlogic/docker-webmail-lite#6]
I installed afterlogic using docker container (https://github.com/afterlogic/docker-webmail-lite) and I'm using post method with the address: https://domain:4444/

I'm getting the following error when trying to login:

![Screenshot at 2022-03-27 11-46-09](https://user-images.githubusercontent.com/87372568/160286998-3269ee02-dec8-416c-bee4-abcb62acc210.png)

**Comment by afterlogic-support** [comment]
Try setting "XFrameOptions" to empty value "" in `data/settings/config.json` configuration file:
https://afterlogic.com/docs/webmail-lite/security/preventing-clickjacking-attacks-with-x-frame-options-header
Does it help? And if it doesn't, see what error you're getting in browser console (F12 key).

**Comment by Sollydus** [comment]
It worked, thank you very much
